package cn.td.etl.utils

/**
 * kafka报文字段
 */
object SourceKafka {

  val DXM_CREDIT_DECISION_NO = "DXM_CREDIT_DECISION_NO"
  val DXM_USE_DECISION_NO = "DXM_USE_DECISION_NO"
  val LX_CREDIT_DECISION_NO = "LX_CREDIT_DECISION_NO"
  val LX_USE_DECISION_NO = "LX_USE_DECISION_NO"
  val ELM_CREDIT_DECISION_NO = "ELM_CREDIT_DECISION_NO"
  val ELM_USE_DECISION_NO = "ELM_USE_DECISION_NO"

}
